services:
  captcha-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: autorize-bot-tg:latest
    container_name: autorize-bot-tg
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
